CLASSNAME:
- fake
- real
DATA:
  BATCHSIZES: 16
  DATA_DIR: RealFakeDB_tiny
  DATA_DIR_HUG: HDanh/RealFakeDB_small
  IMG_SIZE:
  - 224
  - 224
  NUM_WORKERS: 1
MODEL:
  CHECKPOINT: ''
  EPOCHS: 1
  LEARNING_RATE: 1.0e-05
  LOSS_FUNCTION: CrossEntropyLoss
  MODEL_NAME: resnet18
  NUMCLASS: 2
  OPTIM_FUNCTION: Adam
WEIGHT:
  SAVE: true
  SAVE_BEST: true
  SAVE_WEIGHT_EXT_PATH: /content/drive/MyDrive/K32-GoogleDrive/DE_TAI_TOT_NGHIEP/weights
  SAVE_WEIGHT_PATH: weights
